name: demo
on: [workflow_dispatch]
jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: tinoji/delete-older-release-assets@v1.0.0
        with:
          # repo: <owner>/<repoName> # defaults to current repo
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

